[package]
name = "http-client-tls"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
path = "src/http_client_tls.rs"

[dependencies]
eyre.workspace = true
rustls.workspace = true
rustls-platform-verifier.workspace = true
