name: "Build & Test"

on:
  pull_request:
    paths-ignore:
      - "docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    secrets: inherit
