name: "Pin release on Cachix"

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The existing tag to build and pin"
        type: "string"
        required: true

  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  pin:
    if: startsWith(github.ref, 'refs/tags/v')

    strategy:
      fail-fast: false
      matrix:
        runs-on: [
          [self-hosted, linux, ARM64],
          [self-hosted, linux, X64],
          [self-hosted, macOS, ARM64],
          [self-hosted, macOS, X64],
        ]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - name: Configure Cachix
      uses: cachix/cachix-action@v15
      with:
        name: devenv
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Pin release
      run: cachix pin devenv ${{ github.ref_name }} $(nix build --accept-flake-config --print-out-paths)
